services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

  golang:
    build:
      context: ./
      dockerfile: Dockerfile
    command: go run main.go
    ports:
      - '8080:8080'
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /usr/src/app

networks:
  rabbitmq_go_net:
    driver: bridge